server:
    port: 8080


logging:
    level:
        com.elan.erp.frontend: debug
        com.elan.common: debug

spring:
    redis:
        database: 1
        host: localhost
        port: 6379
        pool:
            max-active: 20
    thymeleaf:
        cache: false
        mode: LEGACYHTML5


#注册中心
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

#路由网关
service:
    url: http://erp-gateway-zuul:8767/

#前置登录验证
security:
    login:
        fail: /login
    excludes: /lib,/css,/js,/images,*.ico,*.png,*.jpg,*.gif,*.ttf


ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1