server:
    port: 80
    tomcat:
        #remote-ip-header: x-your-remote-ip-header
        protocol-header: X-Forwarded-For
        accesslog:
            buffered: true # Buffer output such that it is only flushed periodically.
            directory: logs # Directory in which log files are created. Can be relative to the tomcat base dir or absolute.
            enabled: true # Enable access log.
            file-date-format: .yyyy-MM-dd # Date format to place in log file name.
            pattern: "%t [%I] [%{x-access-token}s] %{X-Forwarded-For}i %a %r %b %s (%D ms) " # Format pattern for access logs.
            server.tomcat.accesslog.prefix: access_log # Log file name prefix.
            server.tomcat.accesslog.rename-on-rotate: true # Defer inclusion of the date stamp in the file name until rotate time.
            server.tomcat.accesslog.request-attributes-enabled: true # Set request attributes for IP address, Hostname, protocol and port used for the request.
            server.tomcat.accesslog.rotate: true # Enable access log rotation.
            server.tomcat.accesslog.suffix: .log # Log file name suffix.



logging:
    level:
        com.elan.erp.frontend: info
        com.elan.common: info

spring:
    redis:
        database: 1
        host: localhost
        port: 6379
        pool:
            max-active: 20
    thymeleaf:
        cache: false
        mode: LEGACYHTML5

#注册中心
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:18761/eureka/

#路由网关
service:
    url: http://service-zuul:18767/

#前置登录验证
security:
    login:
        fail: /login
    excludes: /lib,/css,/js,/images,*.ico


ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1